# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Devismart MQTT Java21
version: "0.3.beta3"
slug: devismart-mqtt
description: Devismart MQTT Addon fusing Java 21
url: "https://github.com/barkonar/ha-devireg-mqtt-addon-j21/"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
init: false
startup: application
ports:
  8000/tcp: 8000
services:
  - mqtt:need
map:
  - addon_config:rw
options:
  host: localhost
  port: 1883
  user: ""
  password: ""
schema:
  host: str
  port: port
  user: str
  password: password
