# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Devismart MQTT
version: "0.2.1"
slug: devismart-mqtt
description: Devismart MQTT Addon
url: "https://github.com/bob-tm/ha-devireg-mqtt-addon/"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
init: false
map:
  - addon_config:rw
